### PR TITLE
Live dns

### PR DESCRIPTION
**Pull request by tjamet**

### CODE REVIEW

**Comment by TomOnTime** [comment]
I'm testing this with github.com/StackExchange/dnscontrol and it looks good so far.

* Please fix all "go lint" errors.
* It isn't clear how legacy code should be converted to use LiveDNS. Could you document that?

I'm testing your changes against https://github.com/StackExchange/dnscontrol/tree/gandi-livedns. No luck yet, but I'm looking forward to using live_dns!

**Comment by TomOnTime** [comment]
CC: @captncraig

**Comment by tjamet** [comment]
Hi @TomOnTime I have updated the code to solve linter issues
There are 2 remaining issues that I cannot update unless breaking the API.

Although the lint forces me to break the in-development API, package prefixes has been removed from domain, zone and record structures. For your usage you would need to update [gandi provider](https://github.com/StackExchange/dnscontrol/blob/gandi-livedns/providers/gandi/gandiProvider.go#L55) and change `gandidomain.DomainInfo` for `gandidomain.Info`

This pull request currently implements a straight REST API binding, while trying to stick to similar logic. I will investigate how to provide a migration guide, although the logic between the XML and the REST api seems to have significant changes. And a migration is required to be able to use the REST api instead of the XML one. That could make some migration more difficult.

**Comment by tjamet** [comment]
I have forked your dnscontrol project and have pushed an example [branch](https://github.com/tjamet/dnscontrol/tree/gandi/livedns) to map the live DNS implementation except from the `GetRegistrarCorrections` if this helps
Happy to help if you need

**Comment by TomOnTime** [comment]
about lint: don't break the API just to make lint happy.

about [the dnscontrol branch](https://github.com/tjamet/dnscontrol/tree/gandi/livedns): wow! you're  2 steps ahead of me!  brilliant!

Everythings looks great to me.  Hopefully @prasmussen will get back to you soon.

**Comment by TomOnTime** [comment]
Question: Is there a way to test the v4 and LiveDNS code paths?  For example, if I have two test domains, could I have one use v4 and the other use LiveDNS?

**Comment by tjamet** [comment]
The linter complains about type naming, but those are already in the master head branch:
```
gometalinter --vendor ./client/...
client/client.go:29:21:warning: method Url should be URL (golint)
client/client.go:44:2:warning: struct field Url should be URL (golint)
```

Great that it looks great, I should think of opening the PR to the upstream then :)

I am quite interested in your binding of all DNS providers in dnscontrol, do you think I could use it as a DNS lib in https://github.com/tjamet/mohotani?

**Comment by tjamet** [comment]
I have written some tests for the live DNS, forged real calls on one of my domains but I don't know about any test endpoint on gandi side.
For your integration, you might be interested in using the interface as I did here: https://github.com/tjamet/mohotani/blob/master/dns/provider/gandi/gandi_test.go#L24

**Comment by TomOnTime** [comment]
I think it is ready to upstream, yes.

As far as using dnscontrol as a DNS lib for mohotani... that sounds like an interesting idea!

**Comment by tjamet** [comment]
@TomOnTime I think you can now use the upstream, the PR https://github.com/prasmussen/gandi-api/pull/16 has been merged

**Comment by TomOnTime** [comment]
dnscontrol now has this library vendored. Please rebase
https://github.com/tjamet/dnscontrol/tree/gandi/livedns and submit a PR.

**Comment by tjamet** [comment]
Thanks, I have rebased, I plan to dig into the registrar corrections during this week

**Comment by TomOnTime** [comment]
Awesome!

Which  branch (https://github.com/tjamet/dnscontrol/branches) are you working from?

**Comment by tjamet** [comment]
Hi @TomOnTime I have worked on it yesterday, and just created the PR
I ended up implementing a new provider inspired by the existing one, that only implements the `DNSServiceProvider` interface as changing name servers does not seem to be supported by the current implementation of the live dns api
Shall we go on the discussion on https://github.com/StackExchange/dnscontrol/pull/304 ?

**Comment by tjamet** [comment]
merged in upstream

**Pull request closed without merging**
